// Minimal Database type for Supabase client generics
// In a production app, these would be auto-generated by `supabase gen types typescript`

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    email: string;
                    full_name: string;
                    avatar_url: string | null;
                    role: 'admin' | 'editor' | 'viewer';
                    client_id: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    email: string;
                    full_name?: string;
                    avatar_url?: string | null;
                    role?: 'admin' | 'editor' | 'viewer';
                    client_id?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    email?: string;
                    full_name?: string;
                    avatar_url?: string | null;
                    role?: 'admin' | 'editor' | 'viewer';
                    client_id?: string | null;
                    updated_at?: string;
                };
            };
            // ... existing tables omitted for brevity in thought but will be included in file ...
            // I need to include ALL tables to replace the file correctly.
            clients: {
                Row: {
                    id: string;
                    company_name: string;
                    decision_maker: string;
                    email: string | null;
                    phone: string | null;
                    niche: string;
                    status: 'active' | 'churn' | 'negotiation';
                    contract_value: number;
                    contract_duration: number;
                    start_date: string;
                    ltv: number;
                    drive_link: string | null;
                    notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    company_name: string;
                    decision_maker?: string;
                    email?: string | null;
                    phone?: string | null;
                    niche?: string;
                    status?: string;
                    contract_value?: number;
                    contract_duration?: number;
                    start_date?: string;
                    ltv?: number;
                    drive_link?: string | null;
                    notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    company_name?: string;
                    decision_maker?: string;
                    email?: string | null;
                    phone?: string | null;
                    niche?: string;
                    status?: string;
                    contract_value?: number;
                    contract_duration?: number;
                    start_date?: string;
                    ltv?: number;
                    drive_link?: string | null;
                    notes?: string | null;
                    updated_at?: string;
                };
            };
            tasks: {
                Row: {
                    id: string;
                    title: string;
                    description: string | null;
                    client_id: string | null;
                    assignee_id: string | null;
                    status: 'todo' | 'in_progress' | 'waiting_approval' | 'done';
                    priority: 'low' | 'medium' | 'high' | 'urgent';
                    due_date: string | null;
                    tags: string[];
                    order_index: number;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    title: string;
                    description?: string | null;
                    client_id?: string | null;
                    assignee_id?: string | null;
                    status?: string;
                    priority?: string;
                    due_date?: string | null;
                    tags?: string[];
                    order_index?: number;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    description?: string | null;
                    client_id?: string | null;
                    assignee_id?: string | null;
                    status?: string;
                    priority?: string;
                    due_date?: string | null;
                    tags?: string[];
                    order_index?: number;
                    updated_at?: string;
                };
            };
            rocks: {
                Row: {
                    id: string;
                    title: string;
                    description: string | null;
                    owner_id: string;
                    progress: number;
                    status: 'on_track' | 'off_track' | 'done';
                    quarter: string;
                    due_date: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    title: string;
                    description?: string | null;
                    owner_id: string;
                    progress?: number;
                    status?: string;
                    quarter: string;
                    due_date: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    description?: string | null;
                    owner_id?: string;
                    progress?: number;
                    status?: string;
                    quarter?: string;
                    due_date?: string;
                    updated_at?: string;
                };
            };
            sops: {
                Row: {
                    id: string;
                    title: string;
                    content: string;
                    category: 'projects' | 'areas' | 'resources' | 'archive';
                    client_id: string | null;
                    tags: string[];
                    created_by: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    title: string;
                    content?: string;
                    category?: string;
                    client_id?: string | null;
                    tags?: string[];
                    created_by: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    content?: string;
                    category?: string;
                    client_id?: string | null;
                    tags?: string[];
                    created_by?: string;
                    updated_at?: string;
                };
            };
            approvals: {
                Row: {
                    id: string;
                    task_id: string;
                    client_id: string | null;
                    file_url: string;
                    file_name: string;
                    status: 'pending' | 'approved' | 'rejected';
                    comment: string | null;
                    submitted_by: string;
                    reviewed_by: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    task_id: string;
                    client_id?: string | null;
                    file_url: string;
                    file_name: string;
                    status?: string;
                    comment?: string | null;
                    submitted_by: string;
                    reviewed_by?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    status?: string;
                    comment?: string | null;
                    reviewed_by?: string | null;
                    updated_at?: string;
                };
            };
            pipeline_deals: {
                Row: {
                    id: string;
                    company_name: string;
                    contact_name: string;
                    email: string | null;
                    value: number;
                    stage: 'lead' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
                    probability: number;
                    notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    company_name: string;
                    contact_name?: string;
                    email?: string | null;
                    value?: number;
                    stage?: string;
                    probability?: number;
                    notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    company_name?: string;
                    contact_name?: string;
                    email?: string | null;
                    value?: number;
                    stage?: string;
                    probability?: number;
                    notes?: string | null;
                    updated_at?: string;
                };
            };
            scorecard_metrics: {
                Row: {
                    id: string;
                    name: string;
                    owner_id: string;
                    target: number;
                    actual: number;
                    unit: string;
                    week: string;
                    on_track: boolean;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    owner_id: string;
                    target?: number;
                    actual?: number;
                    unit?: string;
                    week: string;
                    on_track?: boolean;
                    created_at?: string;
                };
                Update: {
                    name?: string;
                    owner_id?: string;
                    target?: number;
                    actual?: number;
                    unit?: string;
                    week?: string;
                    on_track?: boolean;
                };
            };
            client_files: {
                Row: {
                    id: string;
                    client_id: string;
                    file_name: string;
                    file_path: string;
                    file_size: number;
                    mime_type: string;
                    uploaded_by: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    client_id: string;
                    file_name: string;
                    file_path: string;
                    file_size?: number;
                    mime_type?: string;
                    uploaded_by: string;
                    created_at?: string;
                };
                Update: {
                    file_name?: string;
                    file_path?: string;
                    file_size?: number;
                    mime_type?: string;
                };
            };
            // EOS Tables
            meetings_l10: {
                Row: {
                    id: string;
                    title: string;
                    date: string;
                    duration_minutes: number;
                    score: number;
                    status: 'scheduled' | 'in_progress' | 'completed';
                    notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    title?: string;
                    date?: string;
                    duration_minutes?: number;
                    score?: number;
                    status?: string;
                    notes?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    date?: string;
                    duration_minutes?: number;
                    score?: number;
                    status?: string;
                    notes?: string | null;
                    updated_at?: string;
                };
            };
            meeting_issues: {
                Row: {
                    id: string;
                    meeting_id: string;
                    title: string;
                    description: string | null;
                    owner_id: string | null;
                    priority: 'low' | 'medium' | 'high';
                    status: 'open' | 'solved';
                    order_index: number;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    meeting_id: string;
                    title: string;
                    description?: string | null;
                    owner_id?: string | null;
                    priority?: string;
                    status?: string;
                    order_index?: number;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    description?: string | null;
                    owner_id?: string | null;
                    priority?: string;
                    status?: string;
                    order_index?: number;
                    updated_at?: string;
                };
            };
            meeting_headlines: {
                Row: {
                    id: string;
                    meeting_id: string;
                    title: string;
                    type: 'customer' | 'employee' | 'personal';
                    owner_id: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    meeting_id: string;
                    title: string;
                    type: string;
                    owner_id?: string | null;
                    created_at?: string;
                };
                Update: {
                    title?: string;
                    type?: string;
                    owner_id?: string | null;
                };
            };
            meeting_todos: {
                Row: {
                    id: string;
                    meeting_id: string | null;
                    title: string;
                    owner_id: string | null;
                    completed: boolean;
                    due_date: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    meeting_id?: string | null;
                    title: string;
                    owner_id?: string | null;
                    completed?: boolean;
                    due_date?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    title?: string;
                    meeting_id?: string | null;
                    owner_id?: string | null;
                    completed?: boolean;
                    due_date?: string | null;
                    updated_at?: string;
                };
            };
        };
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: Record<string, never>;
    };
}
